# Generated by Django 3.0.5 on 2020-05-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_country_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
