# Generated by Django 3.0.5 on 2020-05-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200502_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='users',
            new_name='user',
        ),
    ]
